/**
 * verify-cardano.cjs — MagicMoney Wallet
 *
 * Standalone verification that our pure Cardano derivation produces addresses
 * IDENTICAL to @emurgo/cardano-serialization-lib (Yoroi/Eternl/Daedalus standard).
 *
 * Run with:  node verify-cardano.cjs
 *
 * The reference vector below was generated by CSL itself for the mnemonic:
 *   "test walk nut penalty hip pave soap entry language right filter choice"
 * If these hardcoded values ever stop matching, the derivation has regressed.
 */

const { pbkdf2 } = require('@noble/hashes/pbkdf2')
const { sha512 } = require('@noble/hashes/sha512')
const { hmac } = require('@noble/hashes/hmac')
const { blake2b } = require('@noble/hashes/blake2b')
const { ed25519 } = require('@noble/curves/ed25519')
const { bech32 } = require('@scure/base')
const bip39 = require('@scure/bip39')
const { wordlist } = require('@scure/bip39/wordlists/english')

const CURVE_N = ed25519.CURVE.n
const HARDEN = 0x80000000
const leToBI = (b) => BigInt('0x' + Buffer.from(b).reverse().toString('hex'))
const biToLE32 = (n) => Buffer.from((n & ((1n << 256n) - 1n)).toString(16).padStart(64, '0'), 'hex').reverse()
const u32 = (n) => { const b = Buffer.alloc(4); b.writeUInt32LE(n >>> 0); return b }

function root(entropy, passphrase = new Uint8Array(0)) {
  const s = pbkdf2(sha512, passphrase, entropy, { c: 4096, dkLen: 96 })
  const kL = Buffer.from(s.slice(0, 32)), kR = Buffer.from(s.slice(32, 64)), c = Buffer.from(s.slice(64, 96))
  kL[0] &= 0b11111000; kL[31] &= 0b00011111; kL[31] |= 0b01000000
  return { kL, kR, c }
}
const pub = (kL) => ed25519.ExtendedPoint.BASE.multiply(leToBI(kL) % CURVE_N).toRawBytes()
function child(p, idx, hard) {
  let Z, I
  if (hard) {
    const i = HARDEN + idx
    Z = hmac(sha512, p.c, Buffer.concat([Buffer.from([0]), p.kL, p.kR, u32(i)]))
    I = hmac(sha512, p.c, Buffer.concat([Buffer.from([1]), p.kL, p.kR, u32(i)]))
  } else {
    const A = pub(p.kL)
    Z = hmac(sha512, p.c, Buffer.concat([Buffer.from([2]), A, u32(idx)]))
    I = hmac(sha512, p.c, Buffer.concat([Buffer.from([3]), A, u32(idx)]))
  }
  return {
    kL: biToLE32(8n * leToBI(Z.slice(0, 28)) + leToBI(p.kL)),
    kR: biToLE32(leToBI(Z.slice(32, 64)) + leToBI(p.kR)),
    c: Buffer.from(I.slice(32, 64))
  }
}
function deriveAddr(mnemonic) {
  const entropy = Buffer.from(bip39.mnemonicToEntropy(mnemonic, wordlist), 'hex')
  let k = root(entropy)
  k = child(k, 1852, true); k = child(k, 1815, true); k = child(k, 0, true)
  const payPub = pub(child(child(k, 0, false), 0, false).kL)
  const stkPub = pub(child(child(k, 2, false), 0, false).kL)
  const payHash = blake2b(payPub, { dkLen: 28 })
  const stkHash = blake2b(stkPub, { dkLen: 28 })
  const addr = bech32.encode('addr', bech32.toWords(Buffer.concat([Buffer.from([0x01]), payHash, stkHash])), 1000)
  const stake = bech32.encode('stake', bech32.toWords(Buffer.concat([Buffer.from([0xe1]), stkHash])), 1000)
  return { addr, stake }
}

// ── Reference vector (produced by @emurgo/cardano-serialization-lib) ─────────
const MNEMONIC = 'test walk nut penalty hip pave soap entry language right filter choice'
const EXPECTED_BASE  = 'addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwqfjkjv7'
const EXPECTED_STAKE = 'stake1uyevw2xnsc0pvn9t9r9c7qryfqfeerchgrlm3ea2nefr9hqxdekzz'

const r = deriveAddr(MNEMONIC)
const baseOk  = r.addr === EXPECTED_BASE
const stakeOk = r.stake === EXPECTED_STAKE

console.log('Base address :', r.addr)
console.log('  expected   :', EXPECTED_BASE)
console.log('  match      :', baseOk ? 'PASS ✅' : 'FAIL ❌')
console.log('Stake address:', r.stake)
console.log('  expected   :', EXPECTED_STAKE)
console.log('  match      :', stakeOk ? 'PASS ✅' : 'FAIL ❌')

process.exit(baseOk && stakeOk ? 0 : 1)
