import path from 'path'
import { makeCapacitorConfig } from './vite.capacitor.shared'

const r = (...p: string[]) => path.resolve(__dirname, ...p)

/**
 * iOS/Capacitor build — the shared native recipe rooted at src/ios.
 *
 * src/ios is deliberately thin: an entry point, a stylesheet, and the two
 * modules below. Everything else resolves into src/capacitor, because the
 * WebView-side code is identical on both native targets. Platform differences
 * live in this alias table, never in runtime `getPlatform()` branches.
 *
 * These two aliases come BEFORE the shared table (makeCapacitorConfig prepends
 * extraAliases) — Vite takes the first match, so a target override must win.
 */
export default makeCapacitorConfig({
  root: 'ios',
  outDir: 'dist-ios',
  // Compiles the in-app self-check in ONLY for the CI job, which sets
  // CAP_WEB_DEBUG=1 (the same flag that makes the WebView inspectable). A
  // literal false lets Rollup drop the whole module from release bundles.
  define: { __MM_SELF_CHECK__: JSON.stringify(process.env.CAP_WEB_DEBUG === '1') },
  // Magic Guard's WKContentRuleList data (~1.3 MB raw-DEFLATE, generated by
  // `npm run magic-guard:ios`). iOS-only: Android blocks with the Rust engine
  // and would just be carrying dead weight in the APK.
  extraCopies: [['resources/magic-guard/ios', 'magic-guard']],
  extraAliases: [
    {
      // Same GitHub-Releases updater as Android, but looking for the .ipa asset
      // instead of the .apk, and never self-disabling (there is no store build
      // of this app — it is sideloaded, so nothing forbids self-updating).
      find: /^\.\/update-check(\.ts)?$/,
      replacement: r('src/ios/update-check.ts')
    },
    {
      // No RoleManager analog on iOS — an app cannot request or even query the
      // default-browser role. The stub reports supported: false.
      find: /^\.\/default-browser(\.ts)?$/,
      replacement: r('src/ios/default-browser.ts')
    },
    {
      // Per-target capability flags (home-screen install, block counters).
      find: /^\.\/platform-caps(\.ts)?$/,
      replacement: r('src/ios/platform-caps.ts')
    },
    {
      // WebAuthn-PRF wallet generation cannot work on iOS: the RP_ID is pinned
      // to 'localhost' but the origin is immovably capacitor://localhost, and
      // passkeys in a WKWebView need the Associated Domains entitlement (paid
      // account). The stub reports unsupported so the buttons stay hidden
      // rather than failing mid-ceremony on the wallet-creation path.
      // Does NOT affect passkey-provider.ts (wallet-as-authenticator), which
      // works on iOS.
      find: /^\.\/passkey(\.ts)?$/,
      replacement: r('src/ios/passkey.ts')
    },
    {
      // Face ID / Touch ID via the Secure Enclave instead of Android's
      // app-enforced gate: the keychain item is bound to .biometryCurrentSet,
      // so the hardware — not the app's control flow — decides whether the
      // wrapping key is released. See SecureVaultPlugin.swift.
      find: /^\.\/biometric(\.ts)?$/,
      replacement: r('src/ios/biometric.ts')
    },
  ]
})
