import path from 'path'
import { makeCapacitorConfig } from './vite.capacitor.shared'

const r = (...p: string[]) => path.resolve(__dirname, ...p)

/**
 * iOS/Capacitor build — the shared native recipe rooted at src/ios.
 *
 * src/ios is deliberately thin: an entry point, a stylesheet, and the two
 * modules below. Everything else resolves into src/capacitor, because the
 * WebView-side code is identical on both native targets. Platform differences
 * live in this alias table, never in runtime `getPlatform()` branches.
 *
 * These two aliases come BEFORE the shared table (makeCapacitorConfig prepends
 * extraAliases) — Vite takes the first match, so a target override must win.
 */
export default makeCapacitorConfig({
  root: 'ios',
  outDir: 'dist-ios',
  // Magic Guard's WKContentRuleList data (~1.3 MB raw-DEFLATE, generated by
  // `npm run magic-guard:ios`). iOS-only: Android blocks with the Rust engine
  // and would just be carrying dead weight in the APK.
  extraCopies: [['resources/magic-guard/ios', 'magic-guard']],
  extraAliases: [
    {
      // Same GitHub-Releases updater as Android, but looking for the .ipa asset
      // instead of the .apk, and never self-disabling (there is no store build
      // of this app — it is sideloaded, so nothing forbids self-updating).
      find: /^\.\/update-check(\.ts)?$/,
      replacement: r('src/ios/update-check.ts')
    },
    {
      // No RoleManager analog on iOS — an app cannot request or even query the
      // default-browser role. The stub reports supported: false.
      find: /^\.\/default-browser(\.ts)?$/,
      replacement: r('src/ios/default-browser.ts')
    },
    {
      // Face ID / Touch ID via the Secure Enclave instead of Android's
      // app-enforced gate: the keychain item is bound to .biometryCurrentSet,
      // so the hardware — not the app's control flow — decides whether the
      // wrapping key is released. See SecureVaultPlugin.swift.
      find: /^\.\/biometric(\.ts)?$/,
      replacement: r('src/ios/biometric.ts')
    },
  ]
})
