package info.chainlens.magicmoney.passkey;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Arrays;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

/**
 * THE CROSS-LANGUAGE CONTRACT.
 *
 * src/main/__fixtures__/webauthn-vectors.json is generated by the TypeScript
 * core (npm run webauthn:vectors). This suite makes the Java port reproduce
 * every field of it byte for byte, starting from the same public test mnemonics.
 *
 * Why it is the deliverable and not a formality: the two implementations sign
 * for the SAME user. If Java derives even one byte differently, a passkey
 * created in Magic Money's own browser silently fails to open in Chrome — and
 * the recovery story ("your 12 words restore it anywhere") becomes false. There
 * is no runtime check that would catch that; this is it.
 *
 * A red test here is a release blocker, not a TODO.
 */
public class WebAuthnVectorsTest {

    private static JSONObject doc;

    @BeforeClass
    public static void loadVectors() throws Exception {
        File file = findVectors();
        String json = new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
        doc = new JSONObject(json);
    }

    /**
     * Walk up from the Gradle working directory (android/app) to the repo root.
     * Searching beats a hardcoded "../../.." so the suite survives being run
     * from the android/ dir, the repo root, or an IDE with its own notion of cwd.
     */
    private static File findVectors() {
        File dir = new File("").getAbsoluteFile();
        for (int i = 0; i < 8 && dir != null; i++) {
            File candidate = new File(dir, "src/main/__fixtures__/webauthn-vectors.json");
            if (candidate.isFile()) return candidate;
            dir = dir.getParentFile();
        }
        throw new IllegalStateException(
                "webauthn-vectors.json not found above " + new File("").getAbsolutePath()
                        + " — run `npm run webauthn:vectors` at the repo root");
    }

    // ── BIP-39, test-only ────────────────────────────────────────────────────
    // Production Java never does this: the provider is handed webauthnRoot and
    // never the seed (see WebAuthnCore's class comment). The suite needs it to
    // prove the chain from the very first byte rather than from a value the TS
    // side simply asserted.
    private static byte[] mnemonicToSeed(String mnemonic) throws Exception {
        SecretKeyFactory f = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
        PBEKeySpec spec = new PBEKeySpec(
                mnemonic.toCharArray(), "mnemonic".getBytes(StandardCharsets.UTF_8), 2048, 512);
        return f.generateSecret(spec).getEncoded();
    }

    private static JSONArray vectors() throws Exception {
        return doc.getJSONArray("vectors");
    }

    // ── The spec block ───────────────────────────────────────────────────────

    @Test
    public void specConstantsMatch() throws Exception {
        JSONObject spec = doc.getJSONObject("spec");
        assertEquals("spec version", "v1", spec.getString("version"));
        assertEquals("aaguid", spec.getString("aaguid"), WebAuthnCore.toHex(WebAuthnCore.AAGUID));
        assertEquals("signCount", 0, spec.getInt("signCount"));
        assertEquals("credentialId version", 1, spec.getInt("credentialIdVersion"));
        assertEquals("attestation format", "none", spec.getString("attestationFormat"));
    }

    /**
     * The AAGUID is documented as SHA-256("magicmoney/webauthn/aaguid/v1")[0..15]
     * precisely so it can be re-derived instead of copy-pasted between languages.
     */
    @Test
    public void aaguidIsDerivedNotPasted() {
        byte[] expected = Arrays.copyOf(
                WebAuthnCore.sha256(WebAuthnCore.utf8("magicmoney/webauthn/aaguid/v1")), 16);
        assertArrayEquals(expected, WebAuthnCore.AAGUID);
    }

    // ── Every vector, every field ────────────────────────────────────────────

    @Test
    public void reproducesEveryVectorByteForByte() throws Exception {
        JSONArray all = vectors();
        assertTrue("expected at least 5 vectors", all.length() >= 5);

        for (int i = 0; i < all.length(); i++) {
            JSONObject v = all.getJSONObject(i);
            String label = v.getString("label");
            String rpId = v.getString("rpId");
            int accountIndex = v.getInt("accountIndex");

            byte[] seed = mnemonicToSeed(v.getString("mnemonic"));
            byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(seed, accountIndex);
            assertEquals(label + ": webauthnRoot", v.getString("webauthnRoot"), WebAuthnCore.toHex(root));

            assertEquals(label + ": macKey", v.getString("macKey"),
                    WebAuthnCore.toHex(WebAuthnCore.deriveCredentialMacKey(root)));
            assertEquals(label + ": rpIdHash", v.getString("rpIdHash"),
                    WebAuthnCore.toHex(WebAuthnCore.rpIdHash(rpId)));

            byte[] nonce = WebAuthnCore.fromHex(v.getString("nonce"));
            WebAuthnCore.CredentialKey key = WebAuthnCore.deriveCredentialKey(root, rpId, nonce);
            assertEquals(label + ": scalarCounter", v.getInt("scalarCounter"), key.counter);
            assertEquals(label + ": privateKey", v.getString("privateKey"), WebAuthnCore.toHex(key.privateKey));
            assertEquals(label + ": publicKey", v.getString("publicKeyUncompressed"),
                    WebAuthnCore.toHex(key.publicKey));
            assertEquals(label + ": x", v.getString("publicKeyX"), WebAuthnCore.toHex(key.x));
            assertEquals(label + ": y", v.getString("publicKeyY"), WebAuthnCore.toHex(key.y));
            assertEquals(label + ": coseKey", v.getString("coseKey"),
                    WebAuthnCore.toHex(WebAuthnCore.coseKeyFromPublicKey(key.publicKey)));

            byte[] credentialId = WebAuthnCore.makeCredentialId(root, rpId, nonce);
            assertEquals(label + ": credentialId", v.getString("credentialId"),
                    WebAuthnCore.toHex(credentialId));
            assertEquals(label + ": credentialId b64u", v.getString("credentialIdBase64url"),
                    WebAuthnCore.base64Url(credentialId));

            JSONObject reg = v.getJSONObject("registration");
            WebAuthnCore.Attestation att =
                    WebAuthnCore.buildAttestationObject(root, rpId, nonce, true, null);
            assertEquals(label + ": authData", reg.getString("authData"), WebAuthnCore.toHex(att.authData));
            assertEquals(label + ": attestationObject", reg.getString("attestationObject"),
                    WebAuthnCore.toHex(att.attestationObject));
            assertArrayEquals(label + ": credentialId in attestation", credentialId, att.credentialId);

            JSONObject as = v.getJSONObject("assertion");
            byte[] clientDataHash = WebAuthnCore.sha256(
                    WebAuthnCore.utf8(as.getString("clientDataHashSource")));
            assertEquals(label + ": clientDataHash", as.getString("clientDataHash"),
                    WebAuthnCore.toHex(clientDataHash));

            WebAuthnCore.Assertion assertion =
                    WebAuthnCore.buildAssertion(root, rpId, credentialId, clientDataHash, true);
            assertEquals(label + ": authenticatorData", as.getString("authenticatorData"),
                    WebAuthnCore.toHex(assertion.authenticatorData));
            // The signature bytes themselves — this is what RFC 6979 + low-S buys
            // us, and the single strongest proof the two ports agree.
            assertEquals(label + ": signature (DER)", as.getString("signatureDer"),
                    WebAuthnCore.toHex(assertion.signature));
        }
    }

    // ── Tamper ───────────────────────────────────────────────────────────────

    @Test
    public void rejectsEveryTamperCaseInTheFixture() throws Exception {
        JSONObject t = doc.getJSONObject("tamper");
        byte[] seed = mnemonicToSeed(t.getString("mnemonic"));
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(seed, t.getInt("accountIndex"));
        String rpId = t.getString("rpId");

        JSONArray cases = t.getJSONArray("mustReject");
        assertTrue("expected tamper cases", cases.length() > 0);
        for (int i = 0; i < cases.length(); i++) {
            JSONObject c = cases.getJSONObject(i);
            String why = c.getString("why");
            byte[] bad = WebAuthnCore.fromHex(c.getString("credentialId"));
            assertFalse("must reject: " + why, WebAuthnCore.isOwnCredentialId(root, rpId, bad));
            try {
                WebAuthnCore.parseCredentialId(root, rpId, bad);
                fail("parseCredentialId should have thrown for: " + why);
            } catch (IllegalArgumentException expected) {
                // Throwing is the contract — never deriving some other key.
            }
        }
    }

    /**
     * Exhaustive, mirroring the TypeScript suite: every single-bit flip across
     * all 33 bytes must be refused. Silently deriving a different key is the
     * failure mode this whole design exists to prevent.
     */
    @Test
    public void rejectsEverySingleBitFlip() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] seed = mnemonicToSeed(v.getString("mnemonic"));
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(seed, v.getInt("accountIndex"));
        String rpId = v.getString("rpId");
        byte[] id = WebAuthnCore.fromHex(v.getString("credentialId"));

        for (int byteIndex = 0; byteIndex < id.length; byteIndex++) {
            for (int bit = 0; bit < 8; bit++) {
                byte[] bad = id.clone();
                bad[byteIndex] ^= (byte) (1 << bit);
                assertFalse("byte " + byteIndex + " bit " + bit,
                        WebAuthnCore.isOwnCredentialId(root, rpId, bad));
            }
        }
        // …and the untouched id is still accepted, so the loop above proves
        // rejection rather than a MAC that refuses everything.
        assertTrue(WebAuthnCore.isOwnCredentialId(root, rpId, id));
    }

    @Test
    public void rejectsWrongLengthsAndVersions() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] seed = mnemonicToSeed(v.getString("mnemonic"));
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(seed, v.getInt("accountIndex"));
        String rpId = v.getString("rpId");
        byte[] id = WebAuthnCore.fromHex(v.getString("credentialId"));

        byte[][] bad = {
                new byte[0],
                Arrays.copyOf(id, id.length - 1),
                Arrays.copyOf(id, id.length + 1),
                new byte[WebAuthnCore.CRED_ID_LEN],
        };
        for (byte[] b : bad) {
            assertFalse(WebAuthnCore.isOwnCredentialId(root, rpId, b));
        }
        assertFalse(WebAuthnCore.isOwnCredentialId(root, rpId, null));
    }

    /** A credential minted for one site must not open another. */
    @Test
    public void refusesCrossSiteAndCrossWalletCredentials() throws Exception {
        JSONArray all = vectors();
        JSONObject a = all.getJSONObject(0);   // foundry / account0 / chainlensnft.info
        JSONObject b = all.getJSONObject(1);   // foundry / account0 / example.com
        JSONObject d = all.getJSONObject(3);   // bip39-zero / account0 / chainlensnft.info

        byte[] rootA = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(a.getString("mnemonic")), a.getInt("accountIndex"));

        assertTrue(WebAuthnCore.isOwnCredentialId(
                rootA, a.getString("rpId"), WebAuthnCore.fromHex(a.getString("credentialId"))));
        assertFalse("another site's credential",
                WebAuthnCore.isOwnCredentialId(rootA, a.getString("rpId"),
                        WebAuthnCore.fromHex(b.getString("credentialId"))));
        assertFalse("another wallet's credential",
                WebAuthnCore.isOwnCredentialId(rootA, a.getString("rpId"),
                        WebAuthnCore.fromHex(d.getString("credentialId"))));
    }

    // ── Properties the vectors alone would not pin ───────────────────────────

    @Test
    public void signsDeterministically() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(v.getString("mnemonic")), v.getInt("accountIndex"));
        String rpId = v.getString("rpId");
        byte[] id = WebAuthnCore.fromHex(v.getString("credentialId"));
        byte[] hash = WebAuthnCore.sha256(WebAuthnCore.utf8("determinism"));

        byte[] first = WebAuthnCore.buildAssertion(root, rpId, id, hash, true).signature;
        byte[] second = WebAuthnCore.buildAssertion(root, rpId, id, hash, true).signature;
        assertArrayEquals("RFC 6979 must give the same k, and so the same bytes", first, second);
    }

    /**
     * Walk the DER and confirm s <= n/2 across many credentials. Without this a
     * high-S signature would still VERIFY at most relying parties, so the only
     * symptom would be a vector mismatch on some future credential — long after
     * the cause was forgotten.
     */
    @Test
    public void normalisesToLowS() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(v.getString("mnemonic")), v.getInt("accountIndex"));
        java.math.BigInteger halfN = new java.math.BigInteger(
                "7fffffff800000007fffffffffffffffde737d56d38bcf4279dce5617e3192a8", 16);

        for (int i = 0; i < 40; i++) {
            String rpId = "lows-" + i + ".example";
            byte[] nonce = new byte[16];
            for (int j = 0; j < 16; j++) nonce[j] = (byte) (j * (i + 1) + 3);
            byte[] id = WebAuthnCore.makeCredentialId(root, rpId, nonce);
            byte[] sig = WebAuthnCore.buildAssertion(
                    root, rpId, id, WebAuthnCore.sha256(WebAuthnCore.utf8("lows-" + i)), true).signature;

            int rLen = sig[3] & 0xff;
            int sLen = sig[4 + rLen + 1] & 0xff;
            byte[] s = Arrays.copyOfRange(sig, 4 + rLen + 2, 4 + rLen + 2 + sLen);
            java.math.BigInteger sInt = new java.math.BigInteger(1, s);
            assertTrue("high-S at iteration " + i, sInt.compareTo(halfN) <= 0);
        }
    }

    @Test
    public void assertionFlagsOmitAttestedData() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(v.getString("mnemonic")), v.getInt("accountIndex"));
        byte[] id = WebAuthnCore.fromHex(v.getString("credentialId"));
        WebAuthnCore.Assertion a = WebAuthnCore.buildAssertion(
                root, v.getString("rpId"), id, new byte[32], true);

        assertEquals("assertion authData is 37 bytes", 37, a.authenticatorData.length);
        int flags = a.authenticatorData[32] & 0xff;
        assertEquals("UP|UV|BE|BS", 0x1d, flags);
        assertEquals("AT must be clear", 0, flags & WebAuthnCore.FLAG_AT);
    }

    @Test
    public void registrationFlagsAndLayout() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(v.getString("mnemonic")), v.getInt("accountIndex"));
        String rpId = v.getString("rpId");
        byte[] nonce = WebAuthnCore.fromHex(v.getString("nonce"));
        WebAuthnCore.Attestation att =
                WebAuthnCore.buildAttestationObject(root, rpId, nonce, true, null);

        byte[] d = att.authData;
        assertArrayEquals(WebAuthnCore.rpIdHash(rpId), Arrays.copyOf(d, 32));
        assertEquals("UP|UV|BE|BS|AT", 0x5d, d[32] & 0xff);
        assertArrayEquals(new byte[]{0, 0, 0, 0}, Arrays.copyOfRange(d, 33, 37));
        assertArrayEquals("real AAGUID on the provider path",
                WebAuthnCore.AAGUID, Arrays.copyOfRange(d, 37, 53));
        assertEquals(WebAuthnCore.CRED_ID_LEN, ((d[53] & 0xff) << 8) | (d[54] & 0xff));
    }

    /**
     * The in-app-browser path zeroes the AAGUID (the client's job, and there we
     * are the client). The provider path must NOT — Chrome does it for us.
     */
    @Test
    public void aaguidIsOverridableForTheShimPath() throws Exception {
        JSONObject v = vectors().getJSONObject(0);
        byte[] root = WebAuthnCore.deriveWebauthnRootFromSeed(
                mnemonicToSeed(v.getString("mnemonic")), v.getInt("accountIndex"));
        WebAuthnCore.Attestation zeroed = WebAuthnCore.buildAttestationObject(
                root, v.getString("rpId"), WebAuthnCore.fromHex(v.getString("nonce")), true, new byte[16]);
        assertArrayEquals(new byte[16], Arrays.copyOfRange(zeroed.authData, 37, 53));
        assertNotEquals(WebAuthnCore.toHex(zeroed.authData),
                v.getJSONObject("registration").getString("authData"));
    }

    @Test
    public void cborPrimitivesMatchTheTypeScriptEncoder() {
        assertEquals("00", WebAuthnCore.toHex(WebAuthnCore.cborInt(0)));
        assertEquals("17", WebAuthnCore.toHex(WebAuthnCore.cborInt(23)));
        assertEquals("1818", WebAuthnCore.toHex(WebAuthnCore.cborInt(24)));
        assertEquals("18ff", WebAuthnCore.toHex(WebAuthnCore.cborInt(255)));
        assertEquals("190100", WebAuthnCore.toHex(WebAuthnCore.cborInt(256)));
        assertEquals("19ffff", WebAuthnCore.toHex(WebAuthnCore.cborInt(65535)));
        assertEquals("1a00010000", WebAuthnCore.toHex(WebAuthnCore.cborInt(65536)));
        assertEquals("20", WebAuthnCore.toHex(WebAuthnCore.cborInt(-1)));
        assertEquals("26", WebAuthnCore.toHex(WebAuthnCore.cborInt(-7)));
        assertEquals("37", WebAuthnCore.toHex(WebAuthnCore.cborInt(-24)));
        assertEquals("3818", WebAuthnCore.toHex(WebAuthnCore.cborInt(-25)));
        assertEquals("40", WebAuthnCore.toHex(WebAuthnCore.cborBytes(new byte[0])));
        assertEquals("420102", WebAuthnCore.toHex(WebAuthnCore.cborBytes(new byte[]{1, 2})));
        assertEquals("60", WebAuthnCore.toHex(WebAuthnCore.cborText("")));
        assertEquals("63666d74", WebAuthnCore.toHex(WebAuthnCore.cborText("fmt")));
        assertEquals("a0", WebAuthnCore.toHex(WebAuthnCore.cborMap()));
    }

    @Test
    public void rejectsAMalformedRootRatherThanDerivingFromIt() {
        try {
            WebAuthnCore.deriveCredentialMacKey(new byte[31]);
            fail("31-byte root should be refused");
        } catch (IllegalArgumentException expected) { /* correct */ }
        try {
            WebAuthnCore.makeCredentialId(new byte[32], "example.com", new byte[15]);
            fail("15-byte nonce should be refused");
        } catch (IllegalArgumentException expected) { /* correct */ }
        try {
            WebAuthnCore.rpIdHash("");
            fail("empty rpId should be refused");
        } catch (IllegalArgumentException expected) { /* correct */ }
    }

    @Test
    public void hexRoundTripsForEveryByteValue() {
        byte[] all = new byte[256];
        for (int i = 0; i < 256; i++) all[i] = (byte) i;
        assertArrayEquals(all, WebAuthnCore.fromHex(WebAuthnCore.toHex(all)));
    }
}
